version: '2'

services:
    redis1:
        container_name: "redis1"
        image: redis-master
        build: ./images/redis-master
        expose:
            - "6379"
        links:
            - redis2
            - redis3
        volumes:
            - ./data/redis1:/data
        networks:
            haredisnet:
                ipv4_address: 10.100.0.1
    redis2:
        container_name: "redis2"
        image: redis-slave
        build: ./images/redis-slave
        expose:
            - "6379"
        volumes:
            - ./data/redis2:/data
        networks:
            haredisnet:
                ipv4_address: 10.100.0.2
    redis3:
        container_name: "redis3"
        image: redis-slave
        build: ./images/redis-slave
        expose:
            - "6379"
        volumes:
            - ./data/redis3:/data
        networks:
            haredisnet:
                ipv4_address: 10.100.0.3
    sentinel1:
        container_name: "sentinel1"
        image: redis-sentinel
        build: ./images/redis-sentinel
        links:
            - redis1
            - redis2
            - redis3
            - sentinel2
            - sentinel3
        networks:
            haredisnet:
    sentinel2:
        container_name: "sentinel2"
        image: redis-sentinel
        build: ./images/redis-sentinel
        links:
            - redis1
            - redis2
            - redis3
        networks:
            haredisnet:
    sentinel3:
        container_name: "sentinel3"
        image: redis-sentinel
        build: ./images/redis-sentinel
        links:
            - redis1
            - redis2
            - redis3
        networks:
            haredisnet:
    checker:
        container_name: "checker"
        image: redis-sentinel-checker
        build: ./images/redis-sentinel-checker
        ports:
            - "9999:9999"
        links:
            - sentinel1
            - sentinel2
            - sentinel3
        networks:
            haredisnet:
    haproxy:
        container_name: "haproxy"
        image: haproxy
        build: ./images/haproxy
        ports:
            - "6379:6379"
            - "8080:8080"
        environment:
            EXTRA_GLOBAL_SETTINGS: debug
        links:
            - redis1
            - redis2
            - redis3
            - sentinel1
            - sentinel2
            - sentinel3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            haredisnet:

networks:
    haredisnet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.100.0.0/24
                  gateway: 10.100.0.244
